USE erp_server;

CREATE UNIQUE INDEX uk_sys_user_username ON sys_user (username);
CREATE UNIQUE INDEX uk_sys_user_employee_no ON sys_user (employee_no);
CREATE UNIQUE INDEX uk_sys_user_mobile ON sys_user (mobile);
CREATE UNIQUE INDEX uk_sys_role_company_role_code ON sys_role (company_id, role_code);
CREATE UNIQUE INDEX uk_sys_menu_menu_code ON sys_menu (menu_code);
CREATE UNIQUE INDEX uk_sys_dept_company_dept_code ON sys_dept (company_id, dept_code);
CREATE UNIQUE INDEX uk_sys_post_company_post_code ON sys_post (company_id, post_code);
CREATE UNIQUE INDEX uk_sys_role_menu_role_id_menu_id ON sys_role_menu (role_id, menu_id);
CREATE UNIQUE INDEX uk_sys_config_config_code ON sys_config (config_code);
CREATE UNIQUE INDEX uk_sys_sequence_rule_biz_type ON sys_sequence_rule (biz_type);
CREATE UNIQUE INDEX uk_md_warehouse_company_warehouse_code ON md_warehouse (company_id, warehouse_code);
CREATE UNIQUE INDEX uk_md_product_company_product_code ON md_product (company_id, product_code);
CREATE UNIQUE INDEX uk_md_customer_company_customer_code ON md_customer (company_id, customer_code);
CREATE UNIQUE INDEX uk_md_supplier_company_supplier_code ON md_supplier (company_id, supplier_code);
CREATE UNIQUE INDEX uk_pur_order_order_no ON pur_order (order_no);
CREATE UNIQUE INDEX uk_pur_receipt_receipt_no ON pur_receipt (receipt_no);
CREATE UNIQUE INDEX uk_pur_return_return_no ON pur_return (return_no);
CREATE UNIQUE INDEX uk_inv_balance_company_warehouse_product ON inv_balance (company_id, warehouse_id, product_id);
CREATE UNIQUE INDEX uk_inv_reservation_company_source_line ON inv_reservation (company_id, source_type, source_line_id);
CREATE UNIQUE INDEX uk_inv_txn_company_biz_line_direction_lot_key ON inv_txn (company_id, biz_type, biz_line_id, direction, lot_key);
CREATE UNIQUE INDEX uk_inv_lot_balance_company_book_wh_product_lot ON inv_lot_balance (company_id, account_book_id, warehouse_id, product_id, lot_no);
CREATE UNIQUE INDEX uk_inv_transfer_transfer_no ON inv_transfer (transfer_no);

CREATE INDEX idx_sys_dept_parent_id ON sys_dept (parent_id);
CREATE INDEX idx_sys_dept_company_parent_sort ON sys_dept (company_id, parent_id, sort_no, id);
CREATE INDEX idx_sys_menu_parent_id ON sys_menu (parent_id);
CREATE INDEX idx_sys_post_dept_id ON sys_post (dept_id);
CREATE INDEX idx_sys_post_company_dept_code ON sys_post (company_id, dept_id, post_code);
CREATE INDEX idx_sys_user_dept_id ON sys_user (dept_id);
CREATE INDEX idx_sys_role_company_deleted_status_code ON sys_role (company_id, deleted_flag, status, role_code);
CREATE INDEX idx_sys_user_role_user_id ON sys_user_role (user_id);
CREATE INDEX idx_sys_user_role_role_id ON sys_user_role (role_id);
CREATE INDEX idx_sys_role_menu_role_id ON sys_role_menu (role_id);
CREATE INDEX idx_sys_role_menu_menu_id ON sys_role_menu (menu_id);
CREATE INDEX idx_sys_login_log_username ON sys_login_log (username);
CREATE INDEX idx_sys_login_log_login_time ON sys_login_log (login_time);
CREATE INDEX idx_sys_operation_log_module ON sys_operation_log (module);
CREATE INDEX idx_sys_operation_log_biz_no ON sys_operation_log (biz_no);
CREATE INDEX idx_sys_operation_log_operation_time ON sys_operation_log (operation_time);
CREATE INDEX idx_sys_audit_log_business ON sys_audit_log (business_type, business_id);
CREATE INDEX idx_sys_audit_log_business_no ON sys_audit_log (business_no);
CREATE INDEX idx_sys_audit_log_audit_time ON sys_audit_log (audit_time);
CREATE INDEX idx_md_warehouse_dept_id ON md_warehouse (dept_id);
CREATE INDEX idx_md_warehouse_manager_user_id ON md_warehouse (manager_user_id);
CREATE INDEX idx_md_warehouse_company_deleted_status_code ON md_warehouse (company_id, deleted_flag, status, warehouse_code);
CREATE INDEX idx_md_warehouse_company_dept_id ON md_warehouse (company_id, dept_id);
CREATE INDEX idx_md_warehouse_company_manager_user_id ON md_warehouse (company_id, manager_user_id);
CREATE INDEX idx_md_product_category_name ON md_product (category_name);
CREATE INDEX idx_md_product_company_deleted_status_code ON md_product (company_id, deleted_flag, status, product_code);
CREATE INDEX idx_md_customer_customer_name ON md_customer (customer_name);
CREATE INDEX idx_md_customer_contact_phone ON md_customer (contact_phone);
CREATE INDEX idx_md_customer_company_deleted_status_code ON md_customer (company_id, deleted_flag, status, customer_code);
CREATE INDEX idx_md_supplier_supplier_name ON md_supplier (supplier_name);
CREATE INDEX idx_md_supplier_contact_phone ON md_supplier (contact_phone);
CREATE INDEX idx_md_supplier_company_deleted_status_code ON md_supplier (company_id, deleted_flag, status, supplier_code);
CREATE INDEX idx_pur_order_supplier_id ON pur_order (supplier_id);
CREATE INDEX idx_pur_order_order_date ON pur_order (order_date);
CREATE INDEX idx_pur_order_status ON pur_order (status);
CREATE INDEX idx_pur_order_line_order_id ON pur_order_line (order_id);
CREATE INDEX idx_pur_receipt_order_id ON pur_receipt (order_id);
CREATE INDEX idx_pur_receipt_line_receipt_id ON pur_receipt_line (receipt_id);
CREATE INDEX idx_pur_return_receipt_id ON pur_return (receipt_id);
CREATE INDEX idx_pur_return_line_return_id ON pur_return_line (return_id);
CREATE INDEX idx_pur_return_line_receipt_line_id ON pur_return_line (receipt_line_id);
CREATE INDEX idx_inv_balance_company_product ON inv_balance (company_id, product_id);
CREATE INDEX idx_inv_reservation_company_source ON inv_reservation (company_id, source_type, source_id);
CREATE INDEX idx_inv_reservation_company_balance ON inv_reservation (company_id, warehouse_id, product_id, status);
CREATE INDEX idx_inv_txn_company_biz_no ON inv_txn (company_id, biz_no);
CREATE INDEX idx_inv_txn_company_biz_line_direction ON inv_txn (company_id, biz_type, biz_line_id, direction);
CREATE INDEX idx_inv_txn_company_warehouse_product ON inv_txn (company_id, warehouse_id, product_id);
CREATE INDEX idx_inv_txn_company_occurred_time ON inv_txn (company_id, occurred_time);
CREATE INDEX idx_inv_txn_company_lot ON inv_txn (company_id, warehouse_id, product_id, lot_no);
CREATE INDEX idx_inv_lot_balance_company_book_product_expiry ON inv_lot_balance (company_id, account_book_id, product_id, expiry_date);
CREATE INDEX idx_inv_lot_balance_company_book_wh_product ON inv_lot_balance (company_id, account_book_id, warehouse_id, product_id);
CREATE INDEX idx_inv_lot_balance_company_book_pick ON inv_lot_balance (company_id, account_book_id, warehouse_id, product_id, expiry_date, first_inbound_time);
CREATE INDEX idx_inv_transfer_from_warehouse_id ON inv_transfer (from_warehouse_id);
CREATE INDEX idx_inv_transfer_to_warehouse_id ON inv_transfer (to_warehouse_id);
CREATE INDEX idx_inv_transfer_line_transfer_id ON inv_transfer_line (transfer_id);
CREATE INDEX idx_inv_transfer_line_product_id ON inv_transfer_line (product_id);
