global:
  resolve_timeout: 5m

route:
  receiver: erp-default
  group_by: [alertname, service, severity]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers: [severity="critical"]
      receiver: erp-critical
      continue: true

receivers:
  - name: erp-default
  - name: erp-critical
