export const contractPageMessages = {
  'zh-CN': {
    contractPage: {
      title: '合同台账', keyword: '关键字', keywordPlaceholder: '合同编号/名称', type: '合同类型', status: '状态', search: '查询', reset: '重置', create: '新建合同', export: '导出', fileName: '合同台账.csv',
      contractNo: '合同编号', contractName: '合同名称', partner: '往来单位', signedDate: '签订日期', effectivePeriod: '有效期', totalAmount: '合同金额', alert: '预警', expiringAlert: '即将到期', lowExecutionAlert: '执行率偏低', actions: '操作', detail: '详情', edit: '编辑', submit: '提交', approve: '审批生效', reject: '驳回', close: '关闭', cancelContract: '作废',
      sales: '销售合同', purchase: '采购合同', customer: '客户', supplier: '供应商', effectiveFrom: '生效日期', effectiveTo: '失效日期', remark: '备注', lines: '合同明细', addLine: '添加明细', product: '商品', quantity: '数量', committedQuantity: '已承诺订单量', availableOrderQuantity: '可下单量', fulfilledQuantity: '已履约', availableFulfillmentQuantity: '可履约量', fulfillmentProgress: '履约进度', unitPrice: '单价', amount: '金额', delete: '删除', save: '保存', cancel: '取消', detailTitle: '合同详情', createTitle: '新建合同', editTitle: '编辑合同',
      statusValue: { draft: '草稿', submitted: '待审批', rejected: '已驳回', active: '生效中', closed: '已关闭', cancelled: '已作废' },
      attachments: '合同附件', uploadAttachment: '上传附件', filename: '文件名', fileSize: '大小', uploadedAt: '上传时间', downloadAttachment: '下载', deleteAttachment: '删除', versions: '版本历史', versionNo: '版本', versionEvent: '变更事件', versionTime: '时间', changedFields: '变更字段', restoreVersion: '恢复为草稿', message: { loadFailed: '加载合同失败', optionsFailed: '加载客户、供应商或商品失败', detailFailed: '加载合同详情失败', completeForm: '请完善合同、往来单位和明细信息', saved: '合同已保存', saveFailed: '保存合同失败', attachmentUploaded: '附件已上传', attachmentFailed: '附件操作失败', actionDone: '操作成功', actionFailed: '合同操作失败', confirmAction: '确认对合同“{name}”执行“{action}”吗？', confirmRestore: '确认从该历史版本创建一份新草稿吗？', prompt: '确认', exported: '合同已导出', restored: '已从历史版本创建新草稿', restoreFailed: '恢复历史版本失败' }
    }
  },
  'en-US': {
    contractPage: {
      title: 'Contract register', keyword: 'Keyword', keywordPlaceholder: 'Contract no. / name', type: 'Contract type', status: 'Status', search: 'Search', reset: 'Reset', create: 'New contract', export: 'Export', fileName: 'contract-register.csv',
      contractNo: 'Contract no.', contractName: 'Contract name', partner: 'Partner', signedDate: 'Signed date', effectivePeriod: 'Effective period', totalAmount: 'Contract amount', alert: 'Alerts', expiringAlert: 'Expiring soon', lowExecutionAlert: 'Low execution', actions: 'Actions', detail: 'Details', edit: 'Edit', submit: 'Submit', approve: 'Approve', reject: 'Reject', close: 'Close', cancelContract: 'Cancel contract',
      sales: 'Sales contract', purchase: 'Purchase contract', customer: 'Customer', supplier: 'Supplier', effectiveFrom: 'Effective from', effectiveTo: 'Effective to', remark: 'Remark', lines: 'Contract lines', addLine: 'Add line', product: 'Product', quantity: 'Quantity', committedQuantity: 'Committed orders', availableOrderQuantity: 'Available to order', fulfilledQuantity: 'Fulfilled', availableFulfillmentQuantity: 'Available to fulfill', fulfillmentProgress: 'Fulfillment progress', unitPrice: 'Unit price', amount: 'Amount', delete: 'Delete', save: 'Save', cancel: 'Cancel', detailTitle: 'Contract details', createTitle: 'New contract', editTitle: 'Edit contract',
      statusValue: { draft: 'Draft', submitted: 'Pending approval', rejected: 'Rejected', active: 'Active', closed: 'Closed', cancelled: 'Cancelled' },
      attachments: 'Contract attachments', uploadAttachment: 'Upload attachment', filename: 'File name', fileSize: 'Size', uploadedAt: 'Uploaded at', downloadAttachment: 'Download', deleteAttachment: 'Delete', versions: 'Version history', versionNo: 'Version', versionEvent: 'Event', versionTime: 'Time', changedFields: 'Changed fields', restoreVersion: 'Restore as draft', message: { loadFailed: 'Failed to load contracts', optionsFailed: 'Failed to load customers, suppliers, or products', detailFailed: 'Failed to load contract details', completeForm: 'Complete the contract, partner, and line information', saved: 'Contract saved', saveFailed: 'Failed to save the contract', attachmentUploaded: 'Attachment uploaded', attachmentFailed: 'Attachment operation failed', actionDone: 'Operation completed', actionFailed: 'Contract operation failed', confirmAction: 'Confirm “{action}” for contract “{name}”?', confirmRestore: 'Create a new draft from this historical version?', prompt: 'Confirmation', exported: 'Contracts exported', restored: 'A new draft was created from the historical version', restoreFailed: 'Failed to restore the historical version' }
    }
  }
} as const
